namespace SchoolApiGW.Services.MarksSheetSetting
{
    public class MarksSheetSettingDto
    {
        public int? ID { get; set; }
        public int ShowMainSubjectMaxMarks { get; set; }
        public int ShowMainSubjectGrades { get; set; }
        public int ShowOptionalSubjectGrades { get; set; }
        public int ShowOptionalSubjectMaxMarks { get; set; }
        public int ShowOptionalSubjectMarks { get; set; }
        public int ShowOverallGrade { get; set; }
        public int ShowOverallPercentage { get; set; }
        public int ShowToppers { get; set; }
        public int ShowOptionalSubjects { get; set; }
        public int ShowMainSubjects { get; set; }
        public int ShowGraph { get; set; }
        public int ShowAttendance { get; set; }
        public int ShowTeacherRemarks { get; set; }
        public int ShowPrincipalRemarks { get; set; }
        public int ShowHeader { get; set; }
        public int ShowFooter { get; set; }
        public int ShowMainSubjectsPercentage { get; set; }
        public int ShowOptionalSubjectsPercentage { get; set; }
        public int ShowPhotograph { get; set; }
        public int ShowFinalResultGrades { get; set; }
        public int ShowFinalResultMarks { get; set; }
        public int ShowFinalResultPercentage { get; set; }
        public int ShowFinalResultMaxMarks { get; set; }
        public int ShowOptionalFinalResultMaxMarks { get; set; }
        public int ShowOptionalFinalResultMarks { get; set; }
        public int ShowOptionalFinalResultGrades { get; set; }
        public int ShowOptionalFinalResultPercentage { get; set; }
        public int ShowOptionalUnitsAlso { get; set; }
        public int ShowDecimalPoints { get; set; }
        public int MarksAlignmentCenter { get; set; }
        public int? TotalMarks { get; set; }
        public int? ShowResult { get; set; }
        public int? ShowPosition { get; set; }
        public int? GraphRightOnOpSubject { get; set; }
        public int ShowMainMaxMarksOnHeader { get; set; }
        public int ShowOptionalMaxMarksOnHeader { get; set; }
        public int ShowMergedRank { get; set; }
        public int ShowGradePoints { get; set; }
        public int ShowMainGradePoints { get; set; }
        public int ShowOptionalGradepoints { get; set; }
        public int ShowFinalResultGradePoints { get; set; }
        public int ShowOptionalFinalResultGradePoint { get; set; }
        public int? ShowMainMarks { get; set; }
        public int? FooterDepartmentWise { get; set; }
        public int? ShowGradeTable { get; set; }
        public int? ShowOptionalGraph { get; set; }
        public int? ShowWorkingDays { get; set; }
        public int? ShowTopTenPositionsOnly { get; set; }
        public int? OnlySingleUnitResultSheetSetting { get; set; }
        public int? ShowSubSubjects { get; set; }
        public int? ShowsubSubjectMarks { get; set; }
        public int? ShowSubSubjectmaxMarks { get; set; }
        public int? ShowSubSubjectMarksinheader { get; set; }
        public int? ShowSubSubjectgradepoints { get; set; }
        public int? ShowSubSubjectpercentage { get; set; }
        public int? ShowSubSubjectgrades { get; set; }
        public int? ShowSubSubjectgraph { get; set; }
        public int? SchoolBasedAssessment { get; set; }
        public int? IsprimaryResult { get; set; }
        public int? ShowOptionalRanks { get; set; }
        public int? ShowGraphwithGradePoints { get; set; }
        public int? showgradePoint { get; set; }
        public int? HigherClassesResult { get; set; }
        public int? ShowCoCurricularSubjects { get; set; }
        public int? ShowCoCurricularSubjectMarks { get; set; }
        public int? ShowCoCurricularGrades { get; set; }
        public int? ShowCoCurricularMaxMarks { get; set; }
        public int? ShowCoCurricularUnitsAlso { get; set; }
        public int? ShowCoCurricularMaxMarksOnHeader { get; set; }
        public int? ShowCoCurricularMarks { get; set; }
        public int? ShowCoCurricularPercentage { get; set; }
        public int? ShowCoCurricularGradePoints { get; set; }
        public int? ShowCoCurricularFinalResultMarks { get; set; }
        public int? ShowCoCurricularFinalResultMaxMarks { get; set; }
        public int? ShowCoCurricularFinalResultGrades { get; set; }
        public int? ShowCoCurricularFinalResultGradePoint { get; set; }
        public int? ShowCoCurricularFinalResultPercentage { get; set; }
        public int? schoolbasedassessmentgrades { get; set; }
        public int? For8thClassResult { get; set; }
    }
}
